### ISSUE TITLE
seem there is something wrong with installing pillow?

### ISSUE THREAD

**Issue by jojogh** [coblo/gui-demo#163]
(base) D:\project\gui-demo>pip install -r requirements.txt
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: PyQt5==5.9 in d:\anaconda3\lib\site-packages (from -r requirements.txt (line 1)) (5.9)
Requirement already satisfied: bitcoin==1.1.42 in d:\anaconda3\lib\site-packages (from -r requirements.txt (line 2)) (1.1.42)
Requirement already satisfied: appdirs==1.4.3 in d:\anaconda3\lib\site-packages (from -r requirements.txt (line 3)) (1.4.3)
Requirement already satisfied: timeago==1.0.7 in d:\anaconda3\lib\site-packages (from -r requirements.txt (line 4)) (1.0.7)
Requirement already satisfied: base58==0.2.5 in d:\anaconda3\lib\site-packages (from -r requirements.txt (line 5)) (0.2.5)
Requirement already satisfied: py-ubjson==0.10.0 in d:\anaconda3\lib\site-packages (from -r requirements.txt (line 6)) (0.10.0)
Requirement already satisfied: mnemonic==0.18 in d:\anaconda3\lib\site-packages (from -r requirements.txt (line 7)) (0.18)
Requirement already satisfied: pycoin==0.80 in d:\anaconda3\lib\site-packages (from -r requirements.txt (line 8)) (0.80)
Requirement already satisfied: qrcode==5.3 in d:\anaconda3\lib\site-packages (from -r requirements.txt (line 9)) (5.3)
Collecting Pillow==4.3.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/e0/82/ec499c78bfe4ecaa91c2f3000040451d187ed0a816d58b8543e29c48827f/Pillow-4.3.0.tar.gz
Processing c:\users\yuanh\appdata\local\pip\cache\wheels\bf\3e\09\3960e466e6dd87320522c4e972d5075825dc847f6b5087cddc\sqlalchemy-1.2.0b1-cp37-cp37m-win_amd64.whl
Processing c:\users\yuanh\appdata\local\pip\cache\wheels\26\1f\2a\171f81d379a1da29bcb0dc4751c3dde5fab2afde4f7fe143ae\mcrpc-0.2.5-py2.py3-none-any.whl
Processing c:\users\yuanh\appdata\local\pip\cache\wheels\94\49\21\c987bae630713a8ea854aed76e5b75bbdc1362d7da385a4bcf\iscc-0.9.9-py2.py3-none-any.whl
Processing c:\users\yuanh\appdata\local\pip\cache\wheels\19\83\2a\994d63c0224e971a7d51eaf070d5a1c60e28534e9d3b562796\docx2txt-0.7-cp37-none-any.whl
Requirement already satisfied: sip<4.20,>=4.19.3 in d:\anaconda3\lib\site-packages (from PyQt5==5.9->-r requirements.txt (line 1)) (4.19.8)
Requirement already satisfied: pbkdf2 in d:\anaconda3\lib\site-packages (from mnemonic==0.18->-r requirements.txt (line 7)) (1.3)
Requirement already satisfied: six in d:\anaconda3\lib\site-packages (from qrcode==5.3->-r requirements.txt (line 9)) (1.12.0)
Requirement already satisfied: olefile in d:\anaconda3\lib\site-packages (from Pillow==4.3.0->-r requirements.txt (line 10)) (0.46)
Requirement already satisfied: simplejson in d:\anaconda3\lib\site-packages (from mcrpc==0.2.5->-r requirements.txt (line 12)) (3.16.0)
Requirement already satisfied: requests in d:\anaconda3\lib\site-packages (from mcrpc==0.2.5->-r requirements.txt (line 12)) (2.22.0)
Collecting xxhash
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/7e/0f/a9daf8f7feef7fe8d3478f8500cc56cb6ce6fffd3566faa227229c4f7cea/xxhash-1.4.2-cp37-cp37m-win_amd64.whl
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in d:\anaconda3\lib\site-packages (from requests->mcrpc==0.2.5->-r requirements.txt (line 12)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda3\lib\site-packages (from requests->mcrpc==0.2.5->-r requirements.txt (line 12)) (2018.11.29)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in d:\anaconda3\lib\site-packages (from requests->mcrpc==0.2.5->-r requirements.txt (line 12)) (1.24.1)
Requirement already satisfied: idna<2.9,>=2.5 in d:\anaconda3\lib\site-packages (from requests->mcrpc==0.2.5->-r requirements.txt (line 12)) (2.8)
Building wheels for collected packages: Pillow
  Building wheel for Pillow (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'd:\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\yuanh\\AppData\\Local\\Temp\\pip-install-p5ibj7ao\\Pillow\\setup.py'"'"'; __file__='"'"'C:\\Users\\yuanh\\AppData\\Local\\Temp\\pip-install-p5ibj7ao\\Pillow\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\yuanh\AppData\Local\Temp\pip-wheel-s07tyd97' --python-tag cp37
       cwd: C:\Users\yuanh\AppData\Local\Temp\pip-install-p5ibj7ao\Pillow\
  Complete output (172 lines):
  Single threaded build for windows
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\PIL
  copying PIL\BdfFontFile.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\BmpImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ContainerIO.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\CurImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\DcxImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\DdsImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\EpsImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ExifTags.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\features.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\FliImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\FontFile.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\FpxImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\FtexImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\GbrImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\GdImageFile.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\GifImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\GimpGradientFile.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\GimpPaletteFile.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\GribStubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\IcnsImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\IcoImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\Image.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImageChops.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImageCms.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImageColor.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImageDraw.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImageDraw2.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImageEnhance.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImageFile.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImageFilter.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImageFont.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImageGrab.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImageMath.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImageMode.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImageMorph.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImageOps.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImagePalette.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImagePath.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImageQt.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImageSequence.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImageShow.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImageStat.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImageTk.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImageTransform.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImageWin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\ImtImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\IptcImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\JpegImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\JpegPresets.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\McIdasImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\MicImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\MpegImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\MpoImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\MspImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\OleFileIO.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\PaletteFile.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\PalmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\PcdImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\PcfFontFile.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\PcxImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\PdfImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\PixarImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\PngImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\PpmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\PsdImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\PSDraw.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\PyAccess.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\SgiImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\SpiderImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\SunImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\TarIO.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\TgaImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\TiffImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\TiffTags.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\version.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\WalImageFile.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\WebPImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\WmfImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\XbmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\XpmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\_binary.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\_tkinter_finder.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\_util.py -> build\lib.win-amd64-3.7\PIL
  copying PIL\__init__.py -> build\lib.win-amd64-3.7\PIL
  running egg_info
  writing Pillow.egg-info\PKG-INFO
  writing dependency_links to Pillow.egg-info\dependency_links.txt
  writing requirements to Pillow.egg-info\requires.txt
  writing top-level names to Pillow.egg-info\top_level.txt
  reading manifest file 'Pillow.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.sh'
  no previously-included directories found matching 'docs\_static'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching 'codecov.yml'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.landscape.yaml'
  warning: no previously-included files found matching '.travis'
  warning: no previously-included files found matching '.travis\*'
  warning: no previously-included files found matching 'appveyor.yml'
  warning: no previously-included files found matching 'build_children.sh'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  writing manifest file 'Pillow.egg-info\SOURCES.txt'
  running build_ext

  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.

  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html

  Traceback (most recent call last):
    File "C:\Users\yuanh\AppData\Local\Temp\pip-install-p5ibj7ao\Pillow\setup.py", line 787, in <module>
      zip_safe=not (debug_build() or PLATFORM_MINGW), )
    File "d:\anaconda3\lib\site-packages\setuptools\__init__.py", line 143, in setup
      return distutils.core.setup(**attrs)
    File "d:\anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "d:\anaconda3\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "d:\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "d:\anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "d:\anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "d:\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "d:\anaconda3\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "d:\anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "d:\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "d:\anaconda3\lib\distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "C:\Users\yuanh\AppData\Local\Temp\pip-install-p5ibj7ao\Pillow\setup.py", line 577, in build_extensions
      raise RequiredDependencyException(f)
  __main__.RequiredDependencyException: zlib

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\yuanh\AppData\Local\Temp\pip-install-p5ibj7ao\Pillow\setup.py", line 799, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:

  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.

  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html

  ----------------------------------------
  ERROR: Failed building wheel for Pillow
  Running setup.py clean for Pillow
Failed to build Pillow
Installing collected packages: Pillow, SQLAlchemy, mcrpc, xxhash, iscc, docx2txt
  Found existing installation: pillow 5.3.0
    Uninstalling pillow-5.3.0:
      Successfully uninstalled pillow-5.3.0
    Running setup.py install for Pillow ... error
    ERROR: Command errored out with exit status 1:
     command: 'd:\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\yuanh\\AppData\\Local\\Temp\\pip-install-p5ibj7ao\\Pillow\\setup.py'"'"'; __file__='"'"'C:\\Users\\yuanh\\AppData\\Local\\Temp\\pip-install-p5ibj7ao\\Pillow\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\yuanh\AppData\Local\Temp\pip-record-8yag620p\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\yuanh\AppData\Local\Temp\pip-install-p5ibj7ao\Pillow\
    Complete output (174 lines):
    Single threaded build for windows
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\PIL
    copying PIL\BdfFontFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\BmpImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ContainerIO.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\CurImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\DcxImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\DdsImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\EpsImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ExifTags.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\features.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\FliImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\FontFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\FpxImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\FtexImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\GbrImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\GdImageFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\GifImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\GimpGradientFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\GimpPaletteFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\GribStubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\IcnsImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\IcoImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\Image.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageChops.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageCms.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageColor.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageDraw.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageDraw2.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageEnhance.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageFilter.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageFont.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageGrab.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageMath.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageMode.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageMorph.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageOps.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImagePalette.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImagePath.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageQt.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageSequence.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageShow.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageStat.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageTk.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageTransform.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImageWin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\ImtImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\IptcImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\JpegImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\JpegPresets.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\McIdasImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\MicImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\MpegImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\MpoImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\MspImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\OleFileIO.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PaletteFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PalmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PcdImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PcfFontFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PcxImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PdfImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PixarImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PngImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PpmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PsdImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PSDraw.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\PyAccess.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\SgiImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\SpiderImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\SunImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\TarIO.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\TgaImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\TiffImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\TiffTags.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\version.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\WalImageFile.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\WebPImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\WmfImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\XbmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\XpmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\_binary.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\_tkinter_finder.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\_util.py -> build\lib.win-amd64-3.7\PIL
    copying PIL\__init__.py -> build\lib.win-amd64-3.7\PIL
    running egg_info
    writing Pillow.egg-info\PKG-INFO
    writing dependency_links to Pillow.egg-info\dependency_links.txt
    writing requirements to Pillow.egg-info\requires.txt
    writing top-level names to Pillow.egg-info\top_level.txt
    reading manifest file 'Pillow.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs\_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.travis'
    warning: no previously-included files found matching '.travis\*'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'Pillow.egg-info\SOURCES.txt'
    running build_ext

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    Traceback (most recent call last):
      File "C:\Users\yuanh\AppData\Local\Temp\pip-install-p5ibj7ao\Pillow\setup.py", line 787, in <module>
        zip_safe=not (debug_build() or PLATFORM_MINGW), )
      File "d:\anaconda3\lib\site-packages\setuptools\__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "d:\anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "d:\anaconda3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "d:\anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "d:\anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "d:\anaconda3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "d:\anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "d:\anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "d:\anaconda3\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "d:\anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "d:\anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "d:\anaconda3\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Users\yuanh\AppData\Local\Temp\pip-install-p5ibj7ao\Pillow\setup.py", line 577, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: zlib

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\yuanh\AppData\Local\Temp\pip-install-p5ibj7ao\Pillow\setup.py", line 799, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    ----------------------------------------
  Rolling back uninstall of pillow
  Moving to d:\anaconda3\lib\site-packages\pil\
   from d:\anaconda3\lib\site-packages\~il
  Moving to d:\anaconda3\lib\site-packages\pillow-5.3.0-py3.7.egg-info
   from d:\anaconda3\lib\site-packages\~illow-5.3.0-py3.7.egg-info
ERROR: Command errored out with exit status 1: 'd:\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\yuanh\\AppData\\Local\\Temp\\pip-install-p5ibj7ao\\Pillow\\setup.py'"'"'; __file__='"'"'C:\\Users\\yuanh\\AppData\\Local\\Temp\\pip-install-p5ibj7ao\\Pillow\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\yuanh\AppData\Local\Temp\pip-record-8yag620p\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by titusz** [comment]
There seems to be an issue with the setup of your environment. It is recommended to install dependencies into a clean virtualenv. Your installation logs show that it first uninstalled "Pillow 5.3.0" and than tried to install the older Pillow==4.3.0 from source. The pillow build process then failed because zlib dependencies are missing. There are binary wheel for Pillow, so you should not need to build it yourself. As a quick fix you may try to install Pillow separately (it does not have to be version 4.3.0). Then remove the "pillow" dependency from `requirements.txt` and try `pip install -r requirements.txt` again.
